export type PageId =
  | 'overview'
  | 'data'
  | 'sources'
  | 'management'
  | 'taxonomy'
  | 'jobs'
  | 'candidate'
  | 'candidate-review'
  | 'job-directed'
  | 'job-records'
  | 'graph'
  | 'graph-heatmap'
  | 'graph-relations'
  | 'graph-clusters'
  | 'talent'
  | 'resume'
  | 'match'
  | 'learning'
  | 'review'

export type StatusTone = 'success' | 'warning' | 'info' | 'danger' | 'neutral'
