import { chromium } from 'file:///C:/Users/10741/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs'
import fs from 'node:fs/promises'
import assert from 'node:assert/strict'

const data = JSON.parse(await fs.readFile('frontend/public/enterprise-industry-graph.json', 'utf8'))
const browser = await chromium.launch({ channel: 'msedge', headless: true })
const page = await browser.newPage({ viewport: { width: 1600, height: 1120 }, deviceScaleFactor: 1 })
page.setDefaultTimeout(30000)
const errors = []
page.on('pageerror', error => errors.push(error.message))
await page.goto('http://127.0.0.1:4176/#/job-graph?view=industry', { waitUntil: 'networkidle' })
await page.waitForSelector('.industry-overview')
assert.equal(await page.locator('.industry-view-tabs button').count(), 4)
assert.equal(await page.locator('.industry-matrix tbody tr').count(), 6)
assert.equal(await page.getByText('企业排行', { exact: true }).count(), 0)
await page.screenshot({ path: 'work/industry-v06-overview.png', fullPage: true })

await page.getByRole('button', { name: '产业链图谱', exact: true }).click()
await page.locator('.industry-category-select button', { hasText: '感知系统' }).click()
assert.equal(await page.locator('.industry-enterprise-grid > button').count(), 12)
const firstPageIds = await page.locator('.industry-enterprise-grid > button').evaluateAll(nodes => nodes.map(node => node.dataset.enterpriseId))
await page.getByRole('button', { name: '家企业下一页', exact: true }).click()
const secondPageIds = await page.locator('.industry-enterprise-grid > button').evaluateAll(nodes => nodes.map(node => node.dataset.enterpriseId))
assert(firstPageIds.every(id => !secondPageIds.includes(id)))
await page.locator('.industry-enterprise-grid > button').first().click()
await page.screenshot({ path: 'work/industry-v06-chain.png', fullPage: true })

const unmapped = data.enterprises.find(e => !e.jobCount && e.recruitmentLinks.length && e.reportedOpenings > 0)
await page.getByRole('textbox', { name: '搜索完整企业库' }).fill(unmapped.name)
await page.locator(`[data-enterprise-id="${unmapped.id}"]`).click()
await page.waitForSelector('.industry-no-jd')
assert(await page.locator('.industry-recruitment a').count() > 0)
await page.screenshot({ path: 'work/industry-v06-recruitment.png', fullPage: true })

const mapped = data.enterprises.find(e => e.jobCount > 100)
await page.getByRole('textbox', { name: '搜索完整企业库' }).fill(mapped.name)
await page.locator(`[data-enterprise-id="${mapped.id}"]`).click()
await page.locator('.industry-job-list > button').first().click()
await page.waitForSelector('.industry-full-jd')
assert((await page.locator('.industry-full-jd').textContent()).length > 50)
await page.screenshot({ path: 'work/industry-v06-jd.png', fullPage: true })

await page.getByRole('button', { name: '所属地区 · 总部地图', exact: true }).click()
await page.waitForSelector('.industry-map')
await page.getByRole('button', { name: /北京总部，/ }).click()
await page.locator('.industry-enterprise-grid > button').first().click()
await page.screenshot({ path: 'work/industry-v06-map.png', fullPage: true })
assert((await page.locator('.industry-directory > .industry-pagination').textContent()).includes('112'))
await page.getByRole('button', { name: '海外企业', exact: true }).click()
const overseasCount = data.enterprises.filter(e => e.companyRegion === '海外').length
assert((await page.locator('.industry-directory > .industry-pagination').textContent()).includes(String(overseasCount)))
await page.getByRole('button', { name: '未定位总部', exact: true }).click()
assert((await page.locator('.industry-directory > .industry-pagination').textContent()).includes(String(data.enterprises.filter(e => !e.headquartersPoint).length)))
await page.getByRole('button', { name: '融资阶段', exact: true }).click()
assert((await page.locator('.industry-directory > .industry-pagination').textContent()).includes('632'))
await page.getByText('仅看暂无 JD 映射', { exact: true }).click()
assert((await page.locator('.industry-directory > .industry-pagination').textContent()).includes('530'))

await page.locator('.job-three-graph-switch button').nth(1).click()
await page.waitForSelector('.technology-ecosystem-canvas')
await page.locator('.job-three-graph-switch button').nth(2).click()
await page.waitForSelector('.standard-role-profile-canvas')
await page.locator('.job-three-graph-switch button').first().click()
await page.waitForSelector('.industry-overview')
await page.setViewportSize({ width: 1100, height: 1000 })
await page.screenshot({ path: 'work/industry-v06-narrow.png', fullPage: true })
assert.equal(errors.length, 0, errors.join('\n'))
console.log(JSON.stringify({ ok: true, enterpriseEntries: data.enterprises.length, unmappedRecruitmentTest: unmapped.name, mappedJdTest: mapped.name, overseasCount, runtimeErrors: errors }, null, 2))
await browser.close()
