"""add emerging role discovery workflow

Revision ID: 20260811_0006
Revises: 20260811_0005
Create Date: 2026-08-11 18:28:49.083395
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260811_0006"
down_revision: str | None = "20260811_0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "biz_role_discovery_run",
        sa.Column(
            "discovery_run_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("run_code", sa.String(length=64), nullable=False),
        sa.Column("mode_code", sa.String(length=32), nullable=False),
        sa.Column("target_date", sa.Date(), nullable=False),
        sa.Column("window_start_date", sa.Date(), nullable=True),
        sa.Column(
            "clustering_run_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column(
            "taxonomy_version_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("selected_technology_ids_json", sa.JSON(), nullable=True),
        sa.Column("query_role_name", sa.String(length=500), nullable=True),
        sa.Column("query_description", sa.Text(), nullable=True),
        sa.Column("algorithm_version", sa.String(length=64), nullable=False),
        sa.Column("parameter_json", sa.JSON(), nullable=False),
        sa.Column("input_snapshot_json", sa.JSON(), nullable=False),
        sa.Column("input_snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("result_summary_json", sa.JSON(), nullable=True),
        sa.Column("run_status_code", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["clustering_run_id"],
            ["biz_job_clustering_run.clustering_run_id"],
            name=op.f("fk_biz_role_discovery_run_clustering_run_id_biz_job_clustering_run"),
        ),
        sa.ForeignKeyConstraint(
            ["taxonomy_version_id"],
            ["md_technology_taxonomy_version.taxonomy_version_id"],
            name=op.f(
                "fk_biz_role_discovery_run_taxonomy_version_id_md_technology_taxonomy_version"
            ),
        ),
        sa.PrimaryKeyConstraint("discovery_run_id", name=op.f("pk_biz_role_discovery_run")),
        sa.UniqueConstraint(
            "mode_code", "algorithm_version", "input_snapshot_hash", name="uk_discovery_input"
        ),
        sa.UniqueConstraint("run_code", name=op.f("uq_biz_role_discovery_run_run_code")),
    )
    op.create_index(
        "idx_discovery_run_mode_status",
        "biz_role_discovery_run",
        ["mode_code", "run_status_code", "target_date"],
        unique=False,
    )
    op.create_table(
        "biz_industry_task_candidate",
        sa.Column(
            "industry_task_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "discovery_run_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("task_code", sa.String(length=64), nullable=False),
        sa.Column("task_name", sa.String(length=500), nullable=False),
        sa.Column("normalized_task_text", sa.Text(), nullable=False),
        sa.Column("action_verb", sa.String(length=100), nullable=True),
        sa.Column("task_object", sa.String(length=500), nullable=True),
        sa.Column("expected_output", sa.String(length=500), nullable=True),
        sa.Column("evidence_strength_score", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("market_support_score", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("existing_role_coverage_score", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("task_gap_score", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("job_count", sa.Integer(), nullable=False),
        sa.Column("organization_count", sa.Integer(), nullable=False),
        sa.Column("source_count", sa.Integer(), nullable=False),
        sa.Column("evidence_status_code", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["discovery_run_id"],
            ["biz_role_discovery_run.discovery_run_id"],
            name=op.f("fk_biz_industry_task_candidate_discovery_run_id_biz_role_discovery_run"),
        ),
        sa.PrimaryKeyConstraint("industry_task_id", name=op.f("pk_biz_industry_task_candidate")),
        sa.UniqueConstraint("discovery_run_id", "task_code", name="uk_discovery_task_code"),
    )
    op.create_index(
        "idx_discovery_task_gap",
        "biz_industry_task_candidate",
        ["discovery_run_id", "task_gap_score"],
        unique=False,
    )
    op.create_table(
        "biz_task_community",
        sa.Column(
            "task_community_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "discovery_run_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("community_code", sa.String(length=64), nullable=False),
        sa.Column("community_label", sa.String(length=500), nullable=False),
        sa.Column("grouping_method_code", sa.String(length=32), nullable=False),
        sa.Column("cohesion_score", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("task_count", sa.Integer(), nullable=False),
        sa.Column("community_snapshot_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["discovery_run_id"],
            ["biz_role_discovery_run.discovery_run_id"],
            name=op.f("fk_biz_task_community_discovery_run_id_biz_role_discovery_run"),
        ),
        sa.PrimaryKeyConstraint("task_community_id", name=op.f("pk_biz_task_community")),
        sa.UniqueConstraint("discovery_run_id", "community_code", name="uk_discovery_community"),
    )
    op.create_table(
        "biz_technology_maturity_snapshot",
        sa.Column(
            "maturity_snapshot_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "discovery_run_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "technology_node_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("maturity_raw_score", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("maturity_explore_score", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("verified_event_count", sa.Integer(), nullable=False),
        sa.Column("evidence_status_code", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["discovery_run_id"],
            ["biz_role_discovery_run.discovery_run_id"],
            name=op.f(
                "fk_biz_technology_maturity_snapshot_discovery_run_id_biz_role_discovery_run"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["technology_node_id"],
            ["md_technology_node.technology_node_id"],
            name=op.f("fk_biz_technology_maturity_snapshot_technology_node_id_md_technology_node"),
        ),
        sa.PrimaryKeyConstraint(
            "maturity_snapshot_id", name=op.f("pk_biz_technology_maturity_snapshot")
        ),
        sa.UniqueConstraint("discovery_run_id", "technology_node_id", name="uk_maturity_run_tech"),
    )
    op.create_table(
        "biz_emerging_role_candidate",
        sa.Column(
            "emerging_role_candidate_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "discovery_run_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "task_community_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("candidate_code", sa.String(length=64), nullable=False),
        sa.Column("proposed_name", sa.String(length=500), nullable=False),
        sa.Column("normalized_name", sa.String(length=500), nullable=False),
        sa.Column("maturity_stage_code", sa.String(length=32), nullable=False),
        sa.Column("workflow_status_code", sa.String(length=32), nullable=False),
        sa.Column("candidate_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column(
            "nearest_job_role_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column("overlap_score", sa.Numeric(precision=7, scale=6), nullable=True),
        sa.Column("classification_code", sa.String(length=32), nullable=False),
        sa.Column("mechanical_card_json", sa.JSON(), nullable=False),
        sa.Column("expression_json", sa.JSON(), nullable=True),
        sa.Column("expression_model_version", sa.String(length=100), nullable=True),
        sa.Column("risk_flags_json", sa.JSON(), nullable=False),
        sa.Column(
            "approved_job_role_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["approved_job_role_id"],
            ["biz_job_role.job_role_id"],
            name=op.f("fk_biz_emerging_role_candidate_approved_job_role_id_biz_job_role"),
        ),
        sa.ForeignKeyConstraint(
            ["discovery_run_id"],
            ["biz_role_discovery_run.discovery_run_id"],
            name=op.f("fk_biz_emerging_role_candidate_discovery_run_id_biz_role_discovery_run"),
        ),
        sa.ForeignKeyConstraint(
            ["nearest_job_role_id"],
            ["biz_job_role.job_role_id"],
            name=op.f("fk_biz_emerging_role_candidate_nearest_job_role_id_biz_job_role"),
        ),
        sa.ForeignKeyConstraint(
            ["task_community_id"],
            ["biz_task_community.task_community_id"],
            name=op.f("fk_biz_emerging_role_candidate_task_community_id_biz_task_community"),
        ),
        sa.PrimaryKeyConstraint(
            "emerging_role_candidate_id", name=op.f("pk_biz_emerging_role_candidate")
        ),
        sa.UniqueConstraint(
            "candidate_code", name=op.f("uq_biz_emerging_role_candidate_candidate_code")
        ),
    )
    op.create_index(
        "idx_emerging_candidate_status",
        "biz_emerging_role_candidate",
        ["workflow_status_code", "maturity_stage_code"],
        unique=False,
    )
    op.create_table(
        "rel_industry_task_technology",
        sa.Column(
            "industry_task_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "technology_node_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("relation_type_code", sa.String(length=32), nullable=False),
        sa.Column("relevance_score", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.ForeignKeyConstraint(
            ["industry_task_id"],
            ["biz_industry_task_candidate.industry_task_id"],
            name=op.f(
                "fk_rel_industry_task_technology_industry_task_id_biz_industry_task_candidate"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["technology_node_id"],
            ["md_technology_node.technology_node_id"],
            name=op.f("fk_rel_industry_task_technology_technology_node_id_md_technology_node"),
        ),
        sa.PrimaryKeyConstraint(
            "industry_task_id", "technology_node_id", name=op.f("pk_rel_industry_task_technology")
        ),
    )
    op.create_table(
        "rel_task_community_member",
        sa.Column(
            "task_community_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "industry_task_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("member_role_code", sa.String(length=32), nullable=False),
        sa.Column("membership_score", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.ForeignKeyConstraint(
            ["industry_task_id"],
            ["biz_industry_task_candidate.industry_task_id"],
            name=op.f("fk_rel_task_community_member_industry_task_id_biz_industry_task_candidate"),
        ),
        sa.ForeignKeyConstraint(
            ["task_community_id"],
            ["biz_task_community.task_community_id"],
            name=op.f("fk_rel_task_community_member_task_community_id_biz_task_community"),
        ),
        sa.PrimaryKeyConstraint(
            "task_community_id", "industry_task_id", name=op.f("pk_rel_task_community_member")
        ),
    )
    op.create_table(
        "biz_candidate_score_component",
        sa.Column(
            "candidate_score_component_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "emerging_role_candidate_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("component_code", sa.String(length=64), nullable=False),
        sa.Column("component_type_code", sa.String(length=16), nullable=False),
        sa.Column("raw_score", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("weight", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("weighted_score", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("explanation_json", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["emerging_role_candidate_id"],
            ["biz_emerging_role_candidate.emerging_role_candidate_id"],
            name=op.f(
                "fk_biz_candidate_score_component_emerging_role_candidate_id_biz_emerging_role_candidate"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "candidate_score_component_id", name=op.f("pk_biz_candidate_score_component")
        ),
        sa.UniqueConstraint(
            "emerging_role_candidate_id", "component_code", name="uk_candidate_score_component"
        ),
    )
    op.create_table(
        "biz_standard_job_description",
        sa.Column(
            "standard_jd_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("standard_jd_code", sa.String(length=64), nullable=False),
        sa.Column(
            "emerging_role_candidate_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "job_role_version_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("title_text", sa.String(length=500), nullable=False),
        sa.Column("content_json", sa.JSON(), nullable=False),
        sa.Column("generation_method_code", sa.String(length=32), nullable=False),
        sa.Column("model_version", sa.String(length=100), nullable=True),
        sa.Column("is_market_evidence", sa.Boolean(), nullable=False),
        sa.Column("approval_status_code", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["emerging_role_candidate_id"],
            ["biz_emerging_role_candidate.emerging_role_candidate_id"],
            name=op.f(
                "fk_biz_standard_job_description_emerging_role_candidate_id_biz_emerging_role_candidate"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["job_role_version_id"],
            ["biz_job_role_version.job_role_version_id"],
            name=op.f("fk_biz_standard_job_description_job_role_version_id_biz_job_role_version"),
        ),
        sa.PrimaryKeyConstraint("standard_jd_id", name=op.f("pk_biz_standard_job_description")),
        sa.UniqueConstraint(
            "emerging_role_candidate_id", "version_no", name="uk_candidate_standard_jd"
        ),
        sa.UniqueConstraint(
            "standard_jd_code", name=op.f("uq_biz_standard_job_description_standard_jd_code")
        ),
    )
    op.create_table(
        "rel_candidate_technology",
        sa.Column(
            "emerging_role_candidate_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "technology_node_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("requirement_type_code", sa.String(length=32), nullable=False),
        sa.Column("importance_score", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("evidence_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["emerging_role_candidate_id"],
            ["biz_emerging_role_candidate.emerging_role_candidate_id"],
            name=op.f(
                "fk_rel_candidate_technology_emerging_role_candidate_id_biz_emerging_role_candidate"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["technology_node_id"],
            ["md_technology_node.technology_node_id"],
            name=op.f("fk_rel_candidate_technology_technology_node_id_md_technology_node"),
        ),
        sa.PrimaryKeyConstraint(
            "emerging_role_candidate_id",
            "technology_node_id",
            name=op.f("pk_rel_candidate_technology"),
        ),
    )
    op.create_table(
        "rel_industry_task_evidence",
        sa.Column(
            "industry_task_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "evidence_span_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "job_posting_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("evidence_type_code", sa.String(length=32), nullable=False),
        sa.Column("support_score", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_span_id"],
            ["biz_evidence_span.evidence_span_id"],
            name=op.f("fk_rel_industry_task_evidence_evidence_span_id_biz_evidence_span"),
        ),
        sa.ForeignKeyConstraint(
            ["industry_task_id"],
            ["biz_industry_task_candidate.industry_task_id"],
            name=op.f("fk_rel_industry_task_evidence_industry_task_id_biz_industry_task_candidate"),
        ),
        sa.ForeignKeyConstraint(
            ["job_posting_id"],
            ["biz_job_posting.job_posting_id"],
            name=op.f("fk_rel_industry_task_evidence_job_posting_id_biz_job_posting"),
        ),
        sa.PrimaryKeyConstraint(
            "industry_task_id", "evidence_span_id", name=op.f("pk_rel_industry_task_evidence")
        ),
    )
    op.create_table(
        "rel_maturity_event_contribution",
        sa.Column(
            "maturity_snapshot_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "milestone_event_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("type_weight", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("relevance_score", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("recency_score", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("source_quality_score", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("contribution_score", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.ForeignKeyConstraint(
            ["maturity_snapshot_id"],
            ["biz_technology_maturity_snapshot.maturity_snapshot_id"],
            name=op.f(
                "fk_rel_maturity_event_contribution_maturity_snapshot_id_biz_technology_maturity_snapshot"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["milestone_event_id"],
            ["biz_milestone_event.milestone_event_id"],
            name=op.f("fk_rel_maturity_event_contribution_milestone_event_id_biz_milestone_event"),
        ),
        sa.PrimaryKeyConstraint(
            "maturity_snapshot_id",
            "milestone_event_id",
            name=op.f("pk_rel_maturity_event_contribution"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rel_maturity_event_contribution")
    op.drop_table("rel_industry_task_evidence")
    op.drop_table("rel_candidate_technology")
    op.drop_table("biz_standard_job_description")
    op.drop_table("biz_candidate_score_component")
    op.drop_table("rel_task_community_member")
    op.drop_table("rel_industry_task_technology")
    op.drop_index("idx_emerging_candidate_status", table_name="biz_emerging_role_candidate")
    op.drop_table("biz_emerging_role_candidate")
    op.drop_table("biz_technology_maturity_snapshot")
    op.drop_table("biz_task_community")
    op.drop_index("idx_discovery_task_gap", table_name="biz_industry_task_candidate")
    op.drop_table("biz_industry_task_candidate")
    op.drop_index("idx_discovery_run_mode_status", table_name="biz_role_discovery_run")
    op.drop_table("biz_role_discovery_run")
    # ### end Alembic commands ###
