"""add job data foundation

Revision ID: 20260811_0002
Revises: 20260811_0001
Create Date: 2026-08-11 14:44:21.601966
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260811_0002"
down_revision: str | None = "20260811_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "md_organization",
        sa.Column(
            "organization_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "source_spreadsheet_row_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column("organization_code", sa.String(length=64), nullable=False),
        sa.Column("canonical_name", sa.String(length=500), nullable=False),
        sa.Column("normalized_name", sa.String(length=500), nullable=False),
        sa.Column("organization_type_code", sa.String(length=32), nullable=False),
        sa.Column("country_code", sa.String(length=16), nullable=True),
        sa.Column("province_name", sa.String(length=100), nullable=True),
        sa.Column("city_name", sa.String(length=100), nullable=True),
        sa.Column("website_url", sa.String(length=1500), nullable=True),
        sa.Column("industry_text", sa.String(length=500), nullable=True),
        sa.Column("source_metadata_json", sa.JSON(), nullable=True),
        sa.Column("organization_status_code", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_spreadsheet_row_id"],
            ["raw_spreadsheet_row.spreadsheet_row_id"],
            name=op.f("fk_md_organization_source_spreadsheet_row_id_raw_spreadsheet_row"),
        ),
        sa.PrimaryKeyConstraint("organization_id", name=op.f("pk_md_organization")),
        sa.UniqueConstraint("organization_code", name=op.f("uq_md_organization_organization_code")),
    )
    op.create_index("idx_org_name", "md_organization", ["normalized_name"], unique=False)
    op.create_index(
        "idx_org_type_region",
        "md_organization",
        ["organization_type_code", "province_name", "city_name"],
        unique=False,
    )
    op.create_table(
        "md_data_source",
        sa.Column(
            "data_source_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "source_file_asset_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column("source_code", sa.String(length=64), nullable=False),
        sa.Column("source_name", sa.String(length=300), nullable=False),
        sa.Column("source_type_code", sa.String(length=32), nullable=False),
        sa.Column(
            "owner_organization_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column("entry_url", sa.String(length=1500), nullable=True),
        sa.Column("content_type_code", sa.String(length=32), nullable=False),
        sa.Column("authority_level_code", sa.String(length=32), nullable=True),
        sa.Column("independent_source_group", sa.String(length=128), nullable=True),
        sa.Column("default_reliability_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("license_note", sa.Text(), nullable=True),
        sa.Column("source_status_code", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_organization_id"],
            ["md_organization.organization_id"],
            name=op.f("fk_md_data_source_owner_organization_id_md_organization"),
        ),
        sa.ForeignKeyConstraint(
            ["source_file_asset_id"],
            ["raw_file_asset.file_asset_id"],
            name=op.f("fk_md_data_source_source_file_asset_id_raw_file_asset"),
        ),
        sa.PrimaryKeyConstraint("data_source_id", name=op.f("pk_md_data_source")),
        sa.UniqueConstraint("source_code", name=op.f("uq_md_data_source_source_code")),
    )
    op.create_table(
        "md_organization_alias",
        sa.Column(
            "organization_alias_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "organization_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "source_spreadsheet_row_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column("alias_text", sa.String(length=500), nullable=False),
        sa.Column("normalized_alias", sa.String(length=500), nullable=False),
        sa.Column("alias_type_code", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["md_organization.organization_id"],
            name=op.f("fk_md_organization_alias_organization_id_md_organization"),
        ),
        sa.ForeignKeyConstraint(
            ["source_spreadsheet_row_id"],
            ["raw_spreadsheet_row.spreadsheet_row_id"],
            name=op.f("fk_md_organization_alias_source_spreadsheet_row_id_raw_spreadsheet_row"),
        ),
        sa.PrimaryKeyConstraint("organization_alias_id", name=op.f("pk_md_organization_alias")),
        sa.UniqueConstraint("organization_id", "normalized_alias", name="uk_org_alias"),
    )
    op.create_index(
        "idx_org_alias_lookup", "md_organization_alias", ["normalized_alias"], unique=False
    )
    op.create_table(
        "raw_source_document",
        sa.Column(
            "source_document_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "source_spreadsheet_row_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column("document_code", sa.String(length=64), nullable=False),
        sa.Column(
            "data_source_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("document_type_code", sa.String(length=32), nullable=False),
        sa.Column("source_record_key", sa.String(length=500), nullable=True),
        sa.Column("canonical_url", sa.String(length=1500), nullable=True),
        sa.Column("document_identity_key", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=1000), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), nullable=False),
        sa.Column("missing_successive_runs", sa.Integer(), nullable=False),
        sa.Column("document_status_code", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            ["md_data_source.data_source_id"],
            name=op.f("fk_raw_source_document_data_source_id_md_data_source"),
        ),
        sa.ForeignKeyConstraint(
            ["source_spreadsheet_row_id"],
            ["raw_spreadsheet_row.spreadsheet_row_id"],
            name=op.f("fk_raw_source_document_source_spreadsheet_row_id_raw_spreadsheet_row"),
        ),
        sa.PrimaryKeyConstraint("source_document_id", name=op.f("pk_raw_source_document")),
        sa.UniqueConstraint(
            "data_source_id", "document_identity_key", name="uk_source_document_identity"
        ),
        sa.UniqueConstraint("document_code", name=op.f("uq_raw_source_document_document_code")),
    )
    op.create_index(
        "idx_document_type_seen",
        "raw_source_document",
        ["document_type_code", "last_seen_at"],
        unique=False,
    )
    op.create_table(
        "raw_source_document_version",
        sa.Column(
            "source_document_version_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "source_document_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("collection_run_id", sa.BigInteger(), nullable=True),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column(
            "previous_version_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "file_asset_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("collected_at", sa.DateTime(), nullable=False),
        sa.Column("source_collected_at", sa.DateTime(), nullable=True),
        sa.Column("valid_from", sa.DateTime(), nullable=False),
        sa.Column("valid_to", sa.DateTime(), nullable=True),
        sa.Column("content_text", sa.Text(), nullable=False),
        sa.Column("content_json", sa.JSON(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("parser_version", sa.String(length=64), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["file_asset_id"],
            ["raw_file_asset.file_asset_id"],
            name=op.f("fk_raw_source_document_version_file_asset_id_raw_file_asset"),
        ),
        sa.ForeignKeyConstraint(
            ["previous_version_id"],
            ["raw_source_document_version.source_document_version_id"],
            name=op.f(
                "fk_raw_source_document_version_previous_version_id_raw_source_document_version"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["raw_source_document.source_document_id"],
            name=op.f("fk_raw_source_document_version_source_document_id_raw_source_document"),
        ),
        sa.PrimaryKeyConstraint(
            "source_document_version_id", name=op.f("pk_raw_source_document_version")
        ),
        sa.UniqueConstraint("source_document_id", "content_hash", name="uk_document_content_hash"),
        sa.UniqueConstraint("source_document_id", "version_no", name="uk_document_version_no"),
    )
    op.create_index(
        "idx_document_current",
        "raw_source_document_version",
        ["source_document_id", "is_current", "valid_from"],
        unique=False,
    )
    op.create_table(
        "biz_document_quality",
        sa.Column(
            "document_quality_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "source_document_version_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("checker_version", sa.String(length=64), nullable=False),
        sa.Column("timeliness_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("completeness_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("noise_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("duplication_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("requirement_inflation_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("ai_generated_risk_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("prompt_injection_risk_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("overall_quality_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("quality_status_code", sa.String(length=32), nullable=False),
        sa.Column("reason_json", sa.JSON(), nullable=True),
        sa.Column(
            "checked_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_document_version_id"],
            ["raw_source_document_version.source_document_version_id"],
            name=op.f(
                "fk_biz_document_quality_source_document_version_id_raw_source_document_version"
            ),
        ),
        sa.PrimaryKeyConstraint("document_quality_id", name=op.f("pk_biz_document_quality")),
        sa.UniqueConstraint(
            "source_document_version_id", "checker_version", name="uk_document_quality_version"
        ),
    )
    op.create_table(
        "biz_duplicate_document_group",
        sa.Column(
            "duplicate_group_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("group_code", sa.String(length=64), nullable=False),
        sa.Column(
            "representative_document_version_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column("detection_method_code", sa.String(length=32), nullable=False),
        sa.Column("algorithm_version", sa.String(length=64), nullable=False),
        sa.Column("member_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["representative_document_version_id"],
            ["raw_source_document_version.source_document_version_id"],
            name=op.f(
                "fk_biz_duplicate_document_group_representative_document_version_id_raw_source_document_version"
            ),
        ),
        sa.PrimaryKeyConstraint("duplicate_group_id", name=op.f("pk_biz_duplicate_document_group")),
        sa.UniqueConstraint("group_code", name=op.f("uq_biz_duplicate_document_group_group_code")),
    )
    op.create_table(
        "biz_evidence_span",
        sa.Column(
            "evidence_span_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "source_document_version_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("span_type_code", sa.String(length=32), nullable=False),
        sa.Column("page_no", sa.Integer(), nullable=True),
        sa.Column("start_offset", sa.Integer(), nullable=True),
        sa.Column("end_offset", sa.Integer(), nullable=True),
        sa.Column("evidence_text", sa.Text(), nullable=False),
        sa.Column("evidence_hash", sa.String(length=64), nullable=False),
        sa.Column("source_reliability_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_document_version_id"],
            ["raw_source_document_version.source_document_version_id"],
            name=op.f(
                "fk_biz_evidence_span_source_document_version_id_raw_source_document_version"
            ),
        ),
        sa.PrimaryKeyConstraint("evidence_span_id", name=op.f("pk_biz_evidence_span")),
        sa.UniqueConstraint("source_document_version_id", "evidence_hash", name="uk_evidence_hash"),
    )
    op.create_table(
        "biz_job_posting",
        sa.Column(
            "job_posting_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "source_spreadsheet_row_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column("job_code", sa.String(length=64), nullable=False),
        sa.Column(
            "source_document_version_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "data_source_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("source_job_id", sa.String(length=300), nullable=True),
        sa.Column("source_group_key", sa.String(length=300), nullable=True),
        sa.Column(
            "organization_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("company_name_raw", sa.String(length=500), nullable=True),
        sa.Column("job_title_raw", sa.String(length=1000), nullable=False),
        sa.Column("job_title_normalized", sa.String(length=500), nullable=False),
        sa.Column("employment_type_code", sa.String(length=32), nullable=True),
        sa.Column("job_level_code", sa.String(length=32), nullable=True),
        sa.Column("region_text", sa.String(length=300), nullable=True),
        sa.Column("salary_text", sa.String(length=300), nullable=True),
        sa.Column("salary_min_monthly_cny", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("salary_max_monthly_cny", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("salary_months_per_year", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("education_code", sa.String(length=32), nullable=True),
        sa.Column("education_text", sa.String(length=200), nullable=True),
        sa.Column("experience_min_years", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("experience_max_years", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("experience_text", sa.String(length=200), nullable=True),
        sa.Column("jd_clean_text", sa.Text(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("collected_at", sa.DateTime(), nullable=False),
        sa.Column("source_collected_at", sa.DateTime(), nullable=True),
        sa.Column("time_quality_code", sa.String(length=32), nullable=False),
        sa.Column("expired_at", sa.DateTime(), nullable=True),
        sa.Column("posting_status_code", sa.String(length=32), nullable=False),
        sa.Column("parse_confidence_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("publish_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("evidence_weight", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("source_metadata_json", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            ["md_data_source.data_source_id"],
            name=op.f("fk_biz_job_posting_data_source_id_md_data_source"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["md_organization.organization_id"],
            name=op.f("fk_biz_job_posting_organization_id_md_organization"),
        ),
        sa.ForeignKeyConstraint(
            ["source_document_version_id"],
            ["raw_source_document_version.source_document_version_id"],
            name=op.f("fk_biz_job_posting_source_document_version_id_raw_source_document_version"),
        ),
        sa.ForeignKeyConstraint(
            ["source_spreadsheet_row_id"],
            ["raw_spreadsheet_row.spreadsheet_row_id"],
            name=op.f("fk_biz_job_posting_source_spreadsheet_row_id_raw_spreadsheet_row"),
        ),
        sa.PrimaryKeyConstraint("job_posting_id", name=op.f("pk_biz_job_posting")),
        sa.UniqueConstraint("job_code", name=op.f("uq_biz_job_posting_job_code")),
        sa.UniqueConstraint(
            "source_document_version_id", name=op.f("uq_biz_job_posting_source_document_version_id")
        ),
    )
    op.create_index(
        "idx_job_org_status",
        "biz_job_posting",
        ["organization_id", "posting_status_code", "collected_at"],
        unique=False,
    )
    op.create_index(
        "idx_job_time_quality",
        "biz_job_posting",
        ["time_quality_code", "source_collected_at"],
        unique=False,
    )
    op.create_index(
        "idx_job_title_time",
        "biz_job_posting",
        ["job_title_normalized", "published_at"],
        unique=False,
    )
    op.create_table(
        "biz_job_requirement",
        sa.Column(
            "job_requirement_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "job_posting_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("requirement_no", sa.Integer(), nullable=False),
        sa.Column("requirement_type_code", sa.String(length=32), nullable=False),
        sa.Column("raw_term", sa.String(length=500), nullable=True),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column(
            "technology_node_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column("capability_id", sa.BigInteger(), nullable=True),
        sa.Column("required_level_code", sa.String(length=32), nullable=True),
        sa.Column("required_level_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("mention_count", sa.Integer(), nullable=False),
        sa.Column("mapping_method_code", sa.String(length=32), nullable=True),
        sa.Column("confidence_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_posting_id"],
            ["biz_job_posting.job_posting_id"],
            name=op.f("fk_biz_job_requirement_job_posting_id_biz_job_posting"),
        ),
        sa.ForeignKeyConstraint(
            ["technology_node_id"],
            ["md_technology_node.technology_node_id"],
            name=op.f("fk_biz_job_requirement_technology_node_id_md_technology_node"),
        ),
        sa.PrimaryKeyConstraint("job_requirement_id", name=op.f("pk_biz_job_requirement")),
        sa.UniqueConstraint("job_posting_id", "requirement_no", name="uk_job_requirement_no"),
        sa.UniqueConstraint(
            "job_posting_id",
            "technology_node_id",
            "requirement_type_code",
            name="uk_job_requirement_technology_type",
        ),
    )
    op.create_index(
        "idx_job_requirement_technology",
        "biz_job_requirement",
        ["technology_node_id", "requirement_type_code", "job_posting_id"],
        unique=False,
    )
    op.create_table(
        "rel_duplicate_document_member",
        sa.Column(
            "duplicate_group_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "source_document_version_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("similarity_score", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("copied_ratio", sa.Numeric(precision=7, scale=6), nullable=True),
        sa.Column("is_representative", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["duplicate_group_id"],
            ["biz_duplicate_document_group.duplicate_group_id"],
            name=op.f(
                "fk_rel_duplicate_document_member_duplicate_group_id_biz_duplicate_document_group"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["source_document_version_id"],
            ["raw_source_document_version.source_document_version_id"],
            name=op.f(
                "fk_rel_duplicate_document_member_source_document_version_id_raw_source_document_version"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "duplicate_group_id",
            "source_document_version_id",
            name=op.f("pk_rel_duplicate_document_member"),
        ),
    )
    op.create_table(
        "rel_job_posting_data_source",
        sa.Column(
            "job_posting_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "data_source_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("source_role_code", sa.String(length=32), nullable=False),
        sa.Column("source_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            ["md_data_source.data_source_id"],
            name=op.f("fk_rel_job_posting_data_source_data_source_id_md_data_source"),
        ),
        sa.ForeignKeyConstraint(
            ["job_posting_id"],
            ["biz_job_posting.job_posting_id"],
            name=op.f("fk_rel_job_posting_data_source_job_posting_id_biz_job_posting"),
        ),
        sa.PrimaryKeyConstraint(
            "job_posting_id", "data_source_id", name=op.f("pk_rel_job_posting_data_source")
        ),
    )
    op.create_table(
        "rel_job_requirement_evidence",
        sa.Column(
            "job_requirement_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "evidence_span_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "matched_alias_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("support_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_span_id"],
            ["biz_evidence_span.evidence_span_id"],
            name=op.f("fk_rel_job_requirement_evidence_evidence_span_id_biz_evidence_span"),
        ),
        sa.ForeignKeyConstraint(
            ["job_requirement_id"],
            ["biz_job_requirement.job_requirement_id"],
            name=op.f("fk_rel_job_requirement_evidence_job_requirement_id_biz_job_requirement"),
        ),
        sa.ForeignKeyConstraint(
            ["matched_alias_id"],
            ["md_technology_alias.technology_alias_id"],
            name=op.f("fk_rel_job_requirement_evidence_matched_alias_id_md_technology_alias"),
        ),
        sa.PrimaryKeyConstraint(
            "job_requirement_id", "evidence_span_id", name=op.f("pk_rel_job_requirement_evidence")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rel_job_requirement_evidence")
    op.drop_table("rel_job_posting_data_source")
    op.drop_table("rel_duplicate_document_member")
    op.drop_index("idx_job_requirement_technology", table_name="biz_job_requirement")
    op.drop_table("biz_job_requirement")
    op.drop_index("idx_job_title_time", table_name="biz_job_posting")
    op.drop_index("idx_job_time_quality", table_name="biz_job_posting")
    op.drop_index("idx_job_org_status", table_name="biz_job_posting")
    op.drop_table("biz_job_posting")
    op.drop_table("biz_evidence_span")
    op.drop_table("biz_duplicate_document_group")
    op.drop_table("biz_document_quality")
    op.drop_index("idx_document_current", table_name="raw_source_document_version")
    op.drop_table("raw_source_document_version")
    op.drop_index("idx_document_type_seen", table_name="raw_source_document")
    op.drop_table("raw_source_document")
    op.drop_index("idx_org_alias_lookup", table_name="md_organization_alias")
    op.drop_table("md_organization_alias")
    op.drop_table("md_data_source")
    op.drop_index("idx_org_type_region", table_name="md_organization")
    op.drop_index("idx_org_name", table_name="md_organization")
    op.drop_table("md_organization")
    # ### end Alembic commands ###
