"""candidate profile matching path

Revision ID: 20260811_0007
Revises: 20260811_0006
Create Date: 2026-08-11 19:39:30.714430
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260811_0007"
down_revision: str | None = "20260811_0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "biz_candidate_profile",
        sa.Column(
            "candidate_profile_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("profile_code", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("profile_status_code", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("candidate_profile_id", name=op.f("pk_biz_candidate_profile")),
        sa.UniqueConstraint("profile_code", name=op.f("uq_biz_candidate_profile_profile_code")),
    )
    op.create_table(
        "raw_resume_document",
        sa.Column(
            "resume_document_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("document_code", sa.String(length=64), nullable=False),
        sa.Column("source_name", sa.String(length=500), nullable=False),
        sa.Column("mime_type", sa.String(length=150), nullable=False),
        sa.Column("input_type_code", sa.String(length=32), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("content_text", sa.Text(), nullable=False),
        sa.Column("safety_status_code", sa.String(length=32), nullable=False),
        sa.Column("parser_version", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("resume_document_id", name=op.f("pk_raw_resume_document")),
        sa.UniqueConstraint("document_code", name=op.f("uq_raw_resume_document_document_code")),
    )
    op.create_index("idx_resume_hash", "raw_resume_document", ["content_hash"], unique=False)
    op.create_table(
        "biz_candidate_profile_version",
        sa.Column(
            "candidate_profile_version_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "candidate_profile_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "resume_document_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("version_code", sa.String(length=64), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column(
            "previous_version_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column("workflow_status_code", sa.String(length=32), nullable=False),
        sa.Column("target_role_text", sa.String(length=500), nullable=True),
        sa.Column("education_text", sa.String(length=500), nullable=True),
        sa.Column("experience_summary", sa.Text(), nullable=True),
        sa.Column("preference_json", sa.JSON(), nullable=False),
        sa.Column("fact_json", sa.JSON(), nullable=False),
        sa.Column("insight_json", sa.JSON(), nullable=False),
        sa.Column("completeness_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("conversation_round_count", sa.Integer(), nullable=False),
        sa.Column("parser_version", sa.String(length=64), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["candidate_profile_id"],
            ["biz_candidate_profile.candidate_profile_id"],
            name=op.f(
                "fk_biz_candidate_profile_version_candidate_profile_id_biz_candidate_profile"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["previous_version_id"],
            ["biz_candidate_profile_version.candidate_profile_version_id"],
            name=op.f(
                "fk_biz_candidate_profile_version_previous_version_id_biz_candidate_profile_version"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["resume_document_id"],
            ["raw_resume_document.resume_document_id"],
            name=op.f("fk_biz_candidate_profile_version_resume_document_id_raw_resume_document"),
        ),
        sa.PrimaryKeyConstraint(
            "candidate_profile_version_id", name=op.f("pk_biz_candidate_profile_version")
        ),
        sa.UniqueConstraint("candidate_profile_id", "version_no", name="uk_profile_version_no"),
        sa.UniqueConstraint(
            "version_code", name=op.f("uq_biz_candidate_profile_version_version_code")
        ),
    )
    op.create_index(
        "idx_profile_version_status",
        "biz_candidate_profile_version",
        ["candidate_profile_id", "workflow_status_code"],
        unique=False,
    )
    op.create_table(
        "biz_candidate_dialogue_turn",
        sa.Column(
            "dialogue_turn_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "candidate_profile_version_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("turn_no", sa.Integer(), nullable=False),
        sa.Column("question_code", sa.String(length=64), nullable=False),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column("answer_text", sa.Text(), nullable=True),
        sa.Column("answer_source_code", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["candidate_profile_version_id"],
            ["biz_candidate_profile_version.candidate_profile_version_id"],
            name=op.f(
                "fk_biz_candidate_dialogue_turn_candidate_profile_version_id_biz_candidate_profile_version"
            ),
        ),
        sa.PrimaryKeyConstraint("dialogue_turn_id", name=op.f("pk_biz_candidate_dialogue_turn")),
        sa.UniqueConstraint(
            "candidate_profile_version_id", "turn_no", name="uk_profile_dialogue_turn"
        ),
    )
    op.create_table(
        "rel_candidate_skill_evidence",
        sa.Column(
            "candidate_skill_evidence_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "candidate_profile_version_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "technology_node_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("raw_mention", sa.String(length=500), nullable=False),
        sa.Column("evidence_text", sa.Text(), nullable=False),
        sa.Column("source_type_code", sa.String(length=32), nullable=False),
        sa.Column("evidence_level_code", sa.String(length=32), nullable=False),
        sa.Column("proficiency_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("confidence_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("user_confirmed", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["candidate_profile_version_id"],
            ["biz_candidate_profile_version.candidate_profile_version_id"],
            name=op.f(
                "fk_rel_candidate_skill_evidence_candidate_profile_version_id_biz_candidate_profile_version"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["technology_node_id"],
            ["md_technology_node.technology_node_id"],
            name=op.f("fk_rel_candidate_skill_evidence_technology_node_id_md_technology_node"),
        ),
        sa.PrimaryKeyConstraint(
            "candidate_skill_evidence_id", name=op.f("pk_rel_candidate_skill_evidence")
        ),
        sa.UniqueConstraint(
            "candidate_profile_version_id",
            "technology_node_id",
            "source_type_code",
            name="uk_profile_skill_source",
        ),
    )
    op.create_index(
        "idx_profile_skill_technology",
        "rel_candidate_skill_evidence",
        ["technology_node_id"],
        unique=False,
    )
    op.create_table(
        "biz_candidate_match_run",
        sa.Column(
            "candidate_match_run_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("run_code", sa.String(length=64), nullable=False),
        sa.Column(
            "candidate_profile_version_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "clustering_run_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("algorithm_version", sa.String(length=64), nullable=False),
        sa.Column("input_snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("result_count", sa.Integer(), nullable=False),
        sa.Column("run_status_code", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["candidate_profile_version_id"],
            ["biz_candidate_profile_version.candidate_profile_version_id"],
            name=op.f(
                "fk_biz_candidate_match_run_candidate_profile_version_id_biz_candidate_profile_version"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["clustering_run_id"],
            ["biz_job_clustering_run.clustering_run_id"],
            name=op.f("fk_biz_candidate_match_run_clustering_run_id_biz_job_clustering_run"),
        ),
        sa.PrimaryKeyConstraint("candidate_match_run_id", name=op.f("pk_biz_candidate_match_run")),
        sa.UniqueConstraint(
            "candidate_profile_version_id",
            "clustering_run_id",
            "algorithm_version",
            "input_snapshot_hash",
            name="uk_candidate_match_snapshot",
        ),
        sa.UniqueConstraint("run_code", name=op.f("uq_biz_candidate_match_run_run_code")),
    )
    op.create_table(
        "biz_candidate_match_result",
        sa.Column(
            "candidate_match_result_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "candidate_match_run_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("result_code", sa.String(length=64), nullable=False),
        sa.Column(
            "job_cluster_version_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "representative_job_posting_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column("rank_no", sa.Integer(), nullable=False),
        sa.Column("overall_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("confidence_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("dimension_json", sa.JSON(), nullable=False),
        sa.Column("recommendation_json", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["candidate_match_run_id"],
            ["biz_candidate_match_run.candidate_match_run_id"],
            name=op.f(
                "fk_biz_candidate_match_result_candidate_match_run_id_biz_candidate_match_run"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["job_cluster_version_id"],
            ["biz_job_cluster_version.job_cluster_version_id"],
            name=op.f(
                "fk_biz_candidate_match_result_job_cluster_version_id_biz_job_cluster_version"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["representative_job_posting_id"],
            ["biz_job_posting.job_posting_id"],
            name=op.f(
                "fk_biz_candidate_match_result_representative_job_posting_id_biz_job_posting"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "candidate_match_result_id", name=op.f("pk_biz_candidate_match_result")
        ),
        sa.UniqueConstraint(
            "candidate_match_run_id", "job_cluster_version_id", name="uk_match_cluster"
        ),
        sa.UniqueConstraint("result_code", name=op.f("uq_biz_candidate_match_result_result_code")),
    )
    op.create_index(
        "idx_match_result_rank",
        "biz_candidate_match_result",
        ["candidate_match_run_id", "rank_no"],
        unique=False,
    )
    op.create_table(
        "biz_candidate_learning_path",
        sa.Column(
            "candidate_learning_path_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("path_code", sa.String(length=64), nullable=False),
        sa.Column(
            "candidate_match_result_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("algorithm_version", sa.String(length=64), nullable=False),
        sa.Column("summary_text", sa.Text(), nullable=False),
        sa.Column("steps_json", sa.JSON(), nullable=False),
        sa.Column("workflow_status_code", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["candidate_match_result_id"],
            ["biz_candidate_match_result.candidate_match_result_id"],
            name=op.f(
                "fk_biz_candidate_learning_path_candidate_match_result_id_biz_candidate_match_result"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "candidate_learning_path_id", name=op.f("pk_biz_candidate_learning_path")
        ),
        sa.UniqueConstraint(
            "candidate_match_result_id", "version_no", name="uk_learning_path_version"
        ),
        sa.UniqueConstraint("path_code", name=op.f("uq_biz_candidate_learning_path_path_code")),
    )
    op.create_table(
        "biz_candidate_match_gap",
        sa.Column(
            "candidate_match_gap_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "candidate_match_result_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "technology_node_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("gap_type_code", sa.String(length=32), nullable=False),
        sa.Column("importance_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("candidate_evidence_json", sa.JSON(), nullable=False),
        sa.Column("job_evidence_json", sa.JSON(), nullable=False),
        sa.Column(
            "transfer_from_technology_node_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column("explanation_text", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["candidate_match_result_id"],
            ["biz_candidate_match_result.candidate_match_result_id"],
            name=op.f(
                "fk_biz_candidate_match_gap_candidate_match_result_id_biz_candidate_match_result"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["technology_node_id"],
            ["md_technology_node.technology_node_id"],
            name=op.f("fk_biz_candidate_match_gap_technology_node_id_md_technology_node"),
        ),
        sa.ForeignKeyConstraint(
            ["transfer_from_technology_node_id"],
            ["md_technology_node.technology_node_id"],
            name=op.f(
                "fk_biz_candidate_match_gap_transfer_from_technology_node_id_md_technology_node"
            ),
        ),
        sa.PrimaryKeyConstraint("candidate_match_gap_id", name=op.f("pk_biz_candidate_match_gap")),
        sa.UniqueConstraint(
            "candidate_match_result_id", "technology_node_id", name="uk_match_gap_technology"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("biz_candidate_match_gap")
    op.drop_table("biz_candidate_learning_path")
    op.drop_index("idx_match_result_rank", table_name="biz_candidate_match_result")
    op.drop_table("biz_candidate_match_result")
    op.drop_table("biz_candidate_match_run")
    op.drop_index("idx_profile_skill_technology", table_name="rel_candidate_skill_evidence")
    op.drop_table("rel_candidate_skill_evidence")
    op.drop_table("biz_candidate_dialogue_turn")
    op.drop_index("idx_profile_version_status", table_name="biz_candidate_profile_version")
    op.drop_table("biz_candidate_profile_version")
    op.drop_index("idx_resume_hash", table_name="raw_resume_document")
    op.drop_table("raw_resume_document")
    op.drop_table("biz_candidate_profile")
    # ### end Alembic commands ###
